// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }
  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}
private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum OnDeviceAiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Policy controlling whether readiness methods may initialize the model.
enum LocalAiInitializationPolicyMessage: Int, CaseIterable {
  /// Only check current status; never start model initialization.
  case never = 0
  /// Initialize only when the model is supported but not ready.
  case whenNeeded = 1
  /// Ask the platform to initialize or refresh readiness before proceeding.
  case always = 2
}

/// Current local AI support and model readiness state.
///
/// Generated class from Pigeon that represents data sent in messages.
struct LocalAiStatusMessage: Hashable, CustomStringConvertible {
  /// Whether this platform, OS, and device can support local AI.
  var isSupported: Bool
  /// Whether generation can run now.
  var isReady: Bool
  /// Whether the native platform can initialize or download the model.
  var canInitialize: Bool
  /// Whether model initialization or download is currently running.
  var isInitializing: Bool
  /// Real initialization progress from 0 to 100, when the platform provides it.
  var initializationProgress: Int64? = nil
  /// Human-readable unavailable or initialization failure reason.
  var reason: String? = nil
  /// Raw platform model status for diagnostics.
  var platformStatus: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LocalAiStatusMessage? {
    let isSupported = pigeonVar_list[0] as! Bool
    let isReady = pigeonVar_list[1] as! Bool
    let canInitialize = pigeonVar_list[2] as! Bool
    let isInitializing = pigeonVar_list[3] as! Bool
    let initializationProgress: Int64? = nilOrValue(pigeonVar_list[4])
    let reason: String? = nilOrValue(pigeonVar_list[5])
    let platformStatus: String? = nilOrValue(pigeonVar_list[6])

    return LocalAiStatusMessage(
      isSupported: isSupported,
      isReady: isReady,
      canInitialize: canInitialize,
      isInitializing: isInitializing,
      initializationProgress: initializationProgress,
      reason: reason,
      platformStatus: platformStatus
    )
  }
  func toList() -> [Any?] {
    return [
      isSupported,
      isReady,
      canInitialize,
      isInitializing,
      initializationProgress,
      reason,
      platformStatus,
    ]
  }
  static func == (lhs: LocalAiStatusMessage, rhs: LocalAiStatusMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return OnDeviceAiPigeonInternal.deepEquals(lhs.isSupported, rhs.isSupported) && OnDeviceAiPigeonInternal.deepEquals(lhs.isReady, rhs.isReady) && OnDeviceAiPigeonInternal.deepEquals(lhs.canInitialize, rhs.canInitialize) && OnDeviceAiPigeonInternal.deepEquals(lhs.isInitializing, rhs.isInitializing) && OnDeviceAiPigeonInternal.deepEquals(lhs.initializationProgress, rhs.initializationProgress) && OnDeviceAiPigeonInternal.deepEquals(lhs.reason, rhs.reason) && OnDeviceAiPigeonInternal.deepEquals(lhs.platformStatus, rhs.platformStatus)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LocalAiStatusMessage")
    OnDeviceAiPigeonInternal.deepHash(value: isSupported, hasher: &hasher)
    OnDeviceAiPigeonInternal.deepHash(value: isReady, hasher: &hasher)
    OnDeviceAiPigeonInternal.deepHash(value: canInitialize, hasher: &hasher)
    OnDeviceAiPigeonInternal.deepHash(value: isInitializing, hasher: &hasher)
    OnDeviceAiPigeonInternal.deepHash(value: initializationProgress, hasher: &hasher)
    OnDeviceAiPigeonInternal.deepHash(value: reason, hasher: &hasher)
    OnDeviceAiPigeonInternal.deepHash(value: platformStatus, hasher: &hasher)
  }

  public var description: String {
    return "LocalAiStatusMessage(isSupported: \(String(describing: isSupported)), isReady: \(String(describing: isReady)), canInitialize: \(String(describing: canInitialize)), isInitializing: \(String(describing: isInitializing)), initializationProgress: \(String(describing: initializationProgress)), reason: \(String(describing: reason)), platformStatus: \(String(describing: platformStatus)))"
  }
}

/// Generation controls passed from Dart to the native model session.
///
/// Generated class from Pigeon that represents data sent in messages.
struct LocalAiGenerationConfigMessage: Hashable, CustomStringConvertible {
  /// Soft cap for generated response length.
  var maxTokens: Int64? = nil
  /// Sampling temperature for the generated response.
  var temperature: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LocalAiGenerationConfigMessage? {
    let maxTokens: Int64? = nilOrValue(pigeonVar_list[0])
    let temperature: Double? = nilOrValue(pigeonVar_list[1])

    return LocalAiGenerationConfigMessage(
      maxTokens: maxTokens,
      temperature: temperature
    )
  }
  func toList() -> [Any?] {
    return [
      maxTokens,
      temperature,
    ]
  }
  static func == (lhs: LocalAiGenerationConfigMessage, rhs: LocalAiGenerationConfigMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return OnDeviceAiPigeonInternal.deepEquals(lhs.maxTokens, rhs.maxTokens) && OnDeviceAiPigeonInternal.deepEquals(lhs.temperature, rhs.temperature)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LocalAiGenerationConfigMessage")
    OnDeviceAiPigeonInternal.deepHash(value: maxTokens, hasher: &hasher)
    OnDeviceAiPigeonInternal.deepHash(value: temperature, hasher: &hasher)
  }

  public var description: String {
    return "LocalAiGenerationConfigMessage(maxTokens: \(String(describing: maxTokens)), temperature: \(String(describing: temperature)))"
  }
}

/// Complete response from a non-streaming native generation request.
///
/// Generated class from Pigeon that represents data sent in messages.
struct LocalAiGenerationResponseMessage: Hashable, CustomStringConvertible {
  /// Generated response text.
  var text: String
  /// Token count if the native framework exposes one.
  var tokenCount: Int64? = nil
  /// Generation duration in milliseconds.
  var durationMs: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LocalAiGenerationResponseMessage? {
    let text = pigeonVar_list[0] as! String
    let tokenCount: Int64? = nilOrValue(pigeonVar_list[1])
    let durationMs: Double? = nilOrValue(pigeonVar_list[2])

    return LocalAiGenerationResponseMessage(
      text: text,
      tokenCount: tokenCount,
      durationMs: durationMs
    )
  }
  func toList() -> [Any?] {
    return [
      text,
      tokenCount,
      durationMs,
    ]
  }
  static func == (lhs: LocalAiGenerationResponseMessage, rhs: LocalAiGenerationResponseMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return OnDeviceAiPigeonInternal.deepEquals(lhs.text, rhs.text) && OnDeviceAiPigeonInternal.deepEquals(lhs.tokenCount, rhs.tokenCount) && OnDeviceAiPigeonInternal.deepEquals(lhs.durationMs, rhs.durationMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LocalAiGenerationResponseMessage")
    OnDeviceAiPigeonInternal.deepHash(value: text, hasher: &hasher)
    OnDeviceAiPigeonInternal.deepHash(value: tokenCount, hasher: &hasher)
    OnDeviceAiPigeonInternal.deepHash(value: durationMs, hasher: &hasher)
  }

  public var description: String {
    return "LocalAiGenerationResponseMessage(text: \(String(describing: text)), tokenCount: \(String(describing: tokenCount)), durationMs: \(String(describing: durationMs)))"
  }
}

/// Snapshot emitted by the native streaming generation request.
///
/// Generated class from Pigeon that represents data sent in messages.
struct LocalAiStreamChunkMessage: Hashable, CustomStringConvertible {
  /// Latest generated text snapshot.
  var text: String
  /// Whether this chunk completes the stream.
  var isDone: Bool
  /// Error code encoded into the stream when generation fails.
  var errorCode: String? = nil
  /// Error message encoded into the stream when generation fails.
  var errorMessage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LocalAiStreamChunkMessage? {
    let text = pigeonVar_list[0] as! String
    let isDone = pigeonVar_list[1] as! Bool
    let errorCode: String? = nilOrValue(pigeonVar_list[2])
    let errorMessage: String? = nilOrValue(pigeonVar_list[3])

    return LocalAiStreamChunkMessage(
      text: text,
      isDone: isDone,
      errorCode: errorCode,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      text,
      isDone,
      errorCode,
      errorMessage,
    ]
  }
  static func == (lhs: LocalAiStreamChunkMessage, rhs: LocalAiStreamChunkMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return OnDeviceAiPigeonInternal.deepEquals(lhs.text, rhs.text) && OnDeviceAiPigeonInternal.deepEquals(lhs.isDone, rhs.isDone) && OnDeviceAiPigeonInternal.deepEquals(lhs.errorCode, rhs.errorCode) && OnDeviceAiPigeonInternal.deepEquals(lhs.errorMessage, rhs.errorMessage)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LocalAiStreamChunkMessage")
    OnDeviceAiPigeonInternal.deepHash(value: text, hasher: &hasher)
    OnDeviceAiPigeonInternal.deepHash(value: isDone, hasher: &hasher)
    OnDeviceAiPigeonInternal.deepHash(value: errorCode, hasher: &hasher)
    OnDeviceAiPigeonInternal.deepHash(value: errorMessage, hasher: &hasher)
  }

  public var description: String {
    return "LocalAiStreamChunkMessage(text: \(String(describing: text)), isDone: \(String(describing: isDone)), errorCode: \(String(describing: errorCode)), errorMessage: \(String(describing: errorMessage)))"
  }
}

private class OnDeviceAiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return LocalAiInitializationPolicyMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return LocalAiStatusMessage.fromList(self.readValue() as! [Any?])
    case 131:
      return LocalAiGenerationConfigMessage.fromList(self.readValue() as! [Any?])
    case 132:
      return LocalAiGenerationResponseMessage.fromList(self.readValue() as! [Any?])
    case 133:
      return LocalAiStreamChunkMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class OnDeviceAiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? LocalAiInitializationPolicyMessage {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? LocalAiStatusMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? LocalAiGenerationConfigMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? LocalAiGenerationResponseMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? LocalAiStreamChunkMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class OnDeviceAiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return OnDeviceAiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return OnDeviceAiPigeonCodecWriter(data: data)
  }
}

class OnDeviceAiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = OnDeviceAiPigeonCodec(readerWriter: OnDeviceAiPigeonCodecReaderWriter())
}

var onDeviceAiPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: OnDeviceAiPigeonCodecReaderWriter());


/// Host methods implemented by each supported platform runner.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol OnDeviceAiHostApi {
  /// Checks the current device, OS, and model readiness.
  func status(completion: @escaping (Result<LocalAiStatusMessage, Error>) -> Void)
  /// Ensures the native model is ready according to [policy].
  func ensureReady(policy: LocalAiInitializationPolicyMessage, completion: @escaping (Result<LocalAiStatusMessage, Error>) -> Void)
  /// Creates a native model session.
  func createSession(instructions: String, completion: @escaping (Result<String, Error>) -> Void)
  /// Releases the native resources associated with [session].
  func disposeSession(session: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Generates a complete response for [prompt] in [session].
  func generateText(session: String, prompt: String, config: LocalAiGenerationConfigMessage, completion: @escaping (Result<LocalAiGenerationResponseMessage, Error>) -> Void)
  /// Starts an asynchronous streaming response for [prompt] in [session].
  func startStreamingText(session: String, prompt: String, config: LocalAiGenerationConfigMessage, completion: @escaping (Result<Void, Error>) -> Void)
  /// Cancels the active streaming response for [session].
  func cancelStreamingText(session: String, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class OnDeviceAiHostApiSetup {
  static var codec: FlutterStandardMessageCodec { OnDeviceAiPigeonCodec.shared }
  /// Sets up an instance of `OnDeviceAiHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: OnDeviceAiHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Checks the current device, OS, and model readiness.
    let statusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_native_ai.OnDeviceAiHostApi.status\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      statusChannel.setMessageHandler { _, reply in
        api.status { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      statusChannel.setMessageHandler(nil)
    }
    /// Ensures the native model is ready according to [policy].
    let ensureReadyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_native_ai.OnDeviceAiHostApi.ensureReady\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      ensureReadyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let policyArg = args[0] as! LocalAiInitializationPolicyMessage
        api.ensureReady(policy: policyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      ensureReadyChannel.setMessageHandler(nil)
    }
    /// Creates a native model session.
    let createSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_native_ai.OnDeviceAiHostApi.createSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let instructionsArg = args[0] as! String
        api.createSession(instructions: instructionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createSessionChannel.setMessageHandler(nil)
    }
    /// Releases the native resources associated with [session].
    let disposeSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_native_ai.OnDeviceAiHostApi.disposeSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg = args[0] as! String
        api.disposeSession(session: sessionArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disposeSessionChannel.setMessageHandler(nil)
    }
    /// Generates a complete response for [prompt] in [session].
    let generateTextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_native_ai.OnDeviceAiHostApi.generateText\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateTextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg = args[0] as! String
        let promptArg = args[1] as! String
        let configArg = args[2] as! LocalAiGenerationConfigMessage
        api.generateText(session: sessionArg, prompt: promptArg, config: configArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateTextChannel.setMessageHandler(nil)
    }
    /// Starts an asynchronous streaming response for [prompt] in [session].
    let startStreamingTextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_native_ai.OnDeviceAiHostApi.startStreamingText\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startStreamingTextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg = args[0] as! String
        let promptArg = args[1] as! String
        let configArg = args[2] as! LocalAiGenerationConfigMessage
        api.startStreamingText(session: sessionArg, prompt: promptArg, config: configArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startStreamingTextChannel.setMessageHandler(nil)
    }
    /// Cancels the active streaming response for [session].
    let cancelStreamingTextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_native_ai.OnDeviceAiHostApi.cancelStreamingText\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelStreamingTextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg = args[0] as! String
        api.cancelStreamingText(session: sessionArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelStreamingTextChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

/// Event stream used for local AI streaming text snapshots.
class GenerationStreamStreamHandler: PigeonEventChannelWrapper<LocalAiStreamChunkMessage> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: GenerationStreamStreamHandler) {
    var channelName = "dev.flutter.pigeon.flutter_native_ai.OnDeviceAiStreamApi.generationStream"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<LocalAiStreamChunkMessage>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: onDeviceAiPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class StatusStreamStreamHandler: PigeonEventChannelWrapper<LocalAiStatusMessage> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: StatusStreamStreamHandler) {
    var channelName = "dev.flutter.pigeon.flutter_native_ai.OnDeviceAiStreamApi.statusStream"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<LocalAiStatusMessage>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: onDeviceAiPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
