// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.bowvie.flutter_on_device_ai

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object OnDeviceAiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Availability state returned by the native local AI bridge.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LocalAiAvailabilityMessage (
  /** Whether generation can run on this host. */
  val isAvailable: Boolean,
  /** Human-readable unavailable reason. */
  val reason: String? = null,
  /** Raw platform model status for diagnostics. */
  val modelStatus: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LocalAiAvailabilityMessage {
      val isAvailable = pigeonVar_list[0] as Boolean
      val reason = pigeonVar_list[1] as String?
      val modelStatus = pigeonVar_list[2] as String?
      return LocalAiAvailabilityMessage(isAvailable, reason, modelStatus)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isAvailable,
      reason,
      modelStatus,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LocalAiAvailabilityMessage
    return OnDeviceAiPigeonUtils.deepEquals(this.isAvailable, other.isAvailable) && OnDeviceAiPigeonUtils.deepEquals(this.reason, other.reason) && OnDeviceAiPigeonUtils.deepEquals(this.modelStatus, other.modelStatus)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + OnDeviceAiPigeonUtils.deepHash(this.isAvailable)
    result = 31 * result + OnDeviceAiPigeonUtils.deepHash(this.reason)
    result = 31 * result + OnDeviceAiPigeonUtils.deepHash(this.modelStatus)
    return result
  }
  override fun toString(): String {
    return "LocalAiAvailabilityMessage(isAvailable=$isAvailable, reason=$reason, modelStatus=$modelStatus)"
  }
}

/**
 * Generation controls passed from Dart to the native model session.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LocalAiGenerationConfigMessage (
  /** Soft cap for generated response length. */
  val maxTokens: Long? = null,
  /** Sampling temperature for the generated response. */
  val temperature: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LocalAiGenerationConfigMessage {
      val maxTokens = pigeonVar_list[0] as Long?
      val temperature = pigeonVar_list[1] as Double?
      return LocalAiGenerationConfigMessage(maxTokens, temperature)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      maxTokens,
      temperature,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LocalAiGenerationConfigMessage
    return OnDeviceAiPigeonUtils.deepEquals(this.maxTokens, other.maxTokens) && OnDeviceAiPigeonUtils.deepEquals(this.temperature, other.temperature)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + OnDeviceAiPigeonUtils.deepHash(this.maxTokens)
    result = 31 * result + OnDeviceAiPigeonUtils.deepHash(this.temperature)
    return result
  }
  override fun toString(): String {
    return "LocalAiGenerationConfigMessage(maxTokens=$maxTokens, temperature=$temperature)"
  }
}

/**
 * Complete response from a non-streaming native generation request.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LocalAiGenerationResponseMessage (
  /** Generated response text. */
  val text: String,
  /** Token count if the native framework exposes one. */
  val tokenCount: Long? = null,
  /** Generation duration in milliseconds. */
  val durationMs: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LocalAiGenerationResponseMessage {
      val text = pigeonVar_list[0] as String
      val tokenCount = pigeonVar_list[1] as Long?
      val durationMs = pigeonVar_list[2] as Double?
      return LocalAiGenerationResponseMessage(text, tokenCount, durationMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      text,
      tokenCount,
      durationMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LocalAiGenerationResponseMessage
    return OnDeviceAiPigeonUtils.deepEquals(this.text, other.text) && OnDeviceAiPigeonUtils.deepEquals(this.tokenCount, other.tokenCount) && OnDeviceAiPigeonUtils.deepEquals(this.durationMs, other.durationMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + OnDeviceAiPigeonUtils.deepHash(this.text)
    result = 31 * result + OnDeviceAiPigeonUtils.deepHash(this.tokenCount)
    result = 31 * result + OnDeviceAiPigeonUtils.deepHash(this.durationMs)
    return result
  }
  override fun toString(): String {
    return "LocalAiGenerationResponseMessage(text=$text, tokenCount=$tokenCount, durationMs=$durationMs)"
  }
}

/**
 * Snapshot emitted by the native streaming generation request.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LocalAiStreamChunkMessage (
  /** Latest generated text snapshot. */
  val text: String,
  /** Whether this chunk completes the stream. */
  val isDone: Boolean,
  /** Error code encoded into the stream when generation fails. */
  val errorCode: String? = null,
  /** Error message encoded into the stream when generation fails. */
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LocalAiStreamChunkMessage {
      val text = pigeonVar_list[0] as String
      val isDone = pigeonVar_list[1] as Boolean
      val errorCode = pigeonVar_list[2] as String?
      val errorMessage = pigeonVar_list[3] as String?
      return LocalAiStreamChunkMessage(text, isDone, errorCode, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      text,
      isDone,
      errorCode,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LocalAiStreamChunkMessage
    return OnDeviceAiPigeonUtils.deepEquals(this.text, other.text) && OnDeviceAiPigeonUtils.deepEquals(this.isDone, other.isDone) && OnDeviceAiPigeonUtils.deepEquals(this.errorCode, other.errorCode) && OnDeviceAiPigeonUtils.deepEquals(this.errorMessage, other.errorMessage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + OnDeviceAiPigeonUtils.deepHash(this.text)
    result = 31 * result + OnDeviceAiPigeonUtils.deepHash(this.isDone)
    result = 31 * result + OnDeviceAiPigeonUtils.deepHash(this.errorCode)
    result = 31 * result + OnDeviceAiPigeonUtils.deepHash(this.errorMessage)
    return result
  }
  override fun toString(): String {
    return "LocalAiStreamChunkMessage(text=$text, isDone=$isDone, errorCode=$errorCode, errorMessage=$errorMessage)"
  }
}
private open class OnDeviceAiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LocalAiAvailabilityMessage.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LocalAiGenerationConfigMessage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LocalAiGenerationResponseMessage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LocalAiStreamChunkMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is LocalAiAvailabilityMessage -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is LocalAiGenerationConfigMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is LocalAiGenerationResponseMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is LocalAiStreamChunkMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val OnDeviceAiPigeonMethodCodec = StandardMethodCodec(OnDeviceAiPigeonCodec())


/**
 * Host methods implemented by each supported platform runner.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface OnDeviceAiHostApi {
  /** Checks whether the current device and OS can run local AI. */
  fun availability(callback: (Result<LocalAiAvailabilityMessage>) -> Unit)
  /** Stores system instructions for subsequent generations. */
  fun initialize(instructions: String, callback: (Result<Unit>) -> Unit)
  /** Generates a complete response for [prompt]. */
  fun generateText(prompt: String, config: LocalAiGenerationConfigMessage, callback: (Result<LocalAiGenerationResponseMessage>) -> Unit)
  /** Starts an asynchronous streaming response for [prompt]. */
  fun startStreamingText(prompt: String, config: LocalAiGenerationConfigMessage, callback: (Result<Unit>) -> Unit)
  /** Cancels the active streaming response. */
  fun cancelStreamingText(callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by OnDeviceAiHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      OnDeviceAiPigeonCodec()
    }
    /** Sets up an instance of `OnDeviceAiHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: OnDeviceAiHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_on_device_ai.OnDeviceAiHostApi.availability$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.availability{ result: Result<LocalAiAvailabilityMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(OnDeviceAiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(OnDeviceAiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_on_device_ai.OnDeviceAiHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val instructionsArg = args[0] as String
            api.initialize(instructionsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(OnDeviceAiPigeonUtils.wrapError(error))
              } else {
                reply.reply(OnDeviceAiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_on_device_ai.OnDeviceAiHostApi.generateText$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val promptArg = args[0] as String
            val configArg = args[1] as LocalAiGenerationConfigMessage
            api.generateText(promptArg, configArg) { result: Result<LocalAiGenerationResponseMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(OnDeviceAiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(OnDeviceAiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_on_device_ai.OnDeviceAiHostApi.startStreamingText$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val promptArg = args[0] as String
            val configArg = args[1] as LocalAiGenerationConfigMessage
            api.startStreamingText(promptArg, configArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(OnDeviceAiPigeonUtils.wrapError(error))
              } else {
                reply.reply(OnDeviceAiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_on_device_ai.OnDeviceAiHostApi.cancelStreamingText$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.cancelStreamingText{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(OnDeviceAiPigeonUtils.wrapError(error))
              } else {
                reply.reply(OnDeviceAiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class OnDeviceAiPigeonStreamHandler<T>(
    val wrapper: OnDeviceAiPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface OnDeviceAiPigeonEventChannelWrapper<T> {
  fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
/** Event stream used for local AI streaming text snapshots. */
abstract class GenerationStreamStreamHandler : OnDeviceAiPigeonEventChannelWrapper<LocalAiStreamChunkMessage> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: GenerationStreamStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.flutter_on_device_ai.OnDeviceAiStreamApi.generationStream"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = OnDeviceAiPigeonStreamHandler<LocalAiStreamChunkMessage>(streamHandler)
      EventChannel(messenger, channelName, OnDeviceAiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from OnDeviceAiPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<LocalAiStreamChunkMessage>) {}

override fun onCancel(p0: Any?) {}
}
      
